name: allium
channels:
  - defaults
dependencies:
  - python=3.8.5
  - pip=23.0.1
  - cmake
  - cython
  - pip:
    - pyyaml==6.0.1
    - pytest==7.1.2
    - joblib==1.2.0
    - scikit-learn==0.23.2
    - numpy==1.19.5
    - pandas>=1.1.5
    - requests
    - gene-thesaurus>=2.2.0
